CREATE TABLE users_cookenu (
	id VARCHAR(255) PRIMARY KEY, 
    name VARCHAR(255) NULL, 
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

DROP TABLE users_cookenu;
ALTER TABLE users_cookenu ADD role ENUM("ADMIN", "NORMAL") NOT NULL DEFAULT "NORMAL"


