POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Hermione",
    "email": "hermione@hogwarts.com",
    "password": "hermione123",
    "role": "normal"
}

###
POST http://localhost:3003/user/follow-user
Content-Type: application/json

{
    "id_user": "24d4ecc2-cfff-46a9-bd73-9122a18d2adf",
    "id_follow_user": "691abef0-ae83-43e1-b158-7684766d4ff7"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "snape@hogwarts.com",
    "password": "hogwarts159"
}

###
GET http://localhost:3003/user/profile-info/:
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2OWQ0N2Q2LTlhNmUtNGI1Yy1hYjA2LTRhZjhjZTQ4MWI0YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NjI5NzY3MywiZXhwIjoxNjc2MzAxMjczfQ.328i-2MFNCZ7dA9E8LKXQaLO_3jnkgt0rTf1rmqmZOE


// recipes -----------------------------
###
POST http://localhost:3003/recipe/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2OWQ0N2Q2LTlhNmUtNGI1Yy1hYjA2LTRhZjhjZTQ4MWI0YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NjQyMzA4MiwiZXhwIjoxNjc2NDI2NjgyfQ.3s9tp_tSUwZexRg-NPQESqbQ3vlSFGYYxEqN47Dv1rQ

{
    "title": "Ovo frito",
    "description": "Coloque um fio de azeite na frigideira. Deixe aquecer. Quebre o ovo na figideira. Salpique uma pitada de sal por todo o ovo. Mantenha em fogo baixo até a clara estar rendada e a gema, mole",
    "creation_date": "2023-02-14",
    "id_author": "b69d47d6-9a6e-4b5c-ab06-4af8ce481b4a"
}

###
GET http://localhost:3003/recipe/feed/24d4ecc2-cfff-46a9-bd73-9122a18d2adf
Content-Type: application/json


