POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Severus Snape",
    "email": "snape@hogwarts.com",
    "password": "hogwarts159",
    "role": "admin"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "snape@hogwarts.com",
    "password": "hogwarts159"
}


