POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Severus Snape",
    "email": "snape@hogwarts.com",
    "password": "hogwarts159",
    "role": "admin"
}

###
POST http://localhost:3003/user/follow-user
Content-Type: application/json

{
    "id_user": "24d4ecc2-cfff-46a9-bd73-9122a18d2adf",
    "id_follow_user": "691abef0-ae83-43e1-b158-7684766d4ff7"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "snape@hogwarts.com",
    "password": "hogwarts159"
}

###
GET http://localhost:3003/user/profile-info/:
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2OWQ0N2Q2LTlhNmUtNGI1Yy1hYjA2LTRhZjhjZTQ4MWI0YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NjI5NzY3MywiZXhwIjoxNjc2MzAxMjczfQ.328i-2MFNCZ7dA9E8LKXQaLO_3jnkgt0rTf1rmqmZOE


// recipes -----------------------------
###
POST http://localhost:3003/recipe/create
Content-Type: application/json

{
    "title": "Chá de camomila",
    "description": "Comece fervendo 250 ml de água; Pegue duas colheres de chá de camomila (a flor seca) e coloque na água; Aguarde aproximadamente 10 minutos com a xícara tampada; Antes de beber, coe. E pronto!",
    "creation_date": "2023-02-14",
    "id_author": "432906d1-3049-43ce-9ac0-1bdd67c472d9"
}

###
GET http://localhost:3003/recipe/feed/24d4ecc2-cfff-46a9-bd73-9122a18d2adf
Content-Type: application/json


